### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [kimhyunkang/markview#1]
Dear @kimhyunkang,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by sergeevabc** [comment]
Is there anything I could do for you to expedite a resolution of this issue?

**Comment by kimhyunkang** [comment]
I'm sorry, but I this project does not (yet) support Windows. The UI is built with WXWindow, so technically it can be compiled in Windows, bit I have never tried to do it, because I don't have a Windows machine.

**Comment by sergeevabc** [comment]
Thank you for letting me know, @kimhyunkang,
